# Generated by Django 4.2.27 on 2026-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='T CLOCK RESTO CAFE', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Time for Tea, Time for Taste', max_length=200)),
                ('address', models.TextField(default='Main Road, Calicut, Kerala')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('gstin', models.CharField(blank=True, default='32ABCDE1234F1Z5', max_length=50)),
                ('footer', models.CharField(blank=True, default='Thank you for visiting T Clock Resto Cafe! 🌴', max_length=200)),
            ],
        ),
    ]
