# Generated by Django 4.2.30 on 2026-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customrole_user_custom_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='color',
        ),
    ]
