# Generated by Django 5.2.16 on 2026-07-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.CharField(blank=True, default='Full', max_length=20),
        ),
    ]
