# Generated by Django 5.2.16 on 2026-07-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='include_gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gpay', 'Google Pay (GPay)'), ('card', 'Credit / Debit Card'), ('upi', 'UPI / QR'), ('split', 'Split Payment'), ('complimentary', 'Complimentary')], default='cash', max_length=20),
        ),
    ]
