# Generated by Django 5.2.16 on 2026-07-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='section',
            field=models.CharField(default='indoor', max_length=50),
        ),
    ]
